const http=require('http');const fs=require('fs');const path=require('path');const{URL}=require('url');const ROOT=__dirname;
function loadEnv(){const f=path.join(ROOT,'.env');if(!fs.existsSync(f))return;for(const line of fs.readFileSync(f,'utf8').split(/\r?\n/)){const s=line.trim();if(!s||s.startsWith('#'))continue;const i=s.indexOf('=');if(i<1)continue;const k=s.slice(0,i).trim();let v=s.slice(i+1).trim();if((v.startsWith('"')&&v.endsWith('"'))||(v.startsWith("'")&&v.endsWith("'")))v=v.slice(1,-1);if(process.env[k]==null)process.env[k]=v}}loadEnv();
const PORT=Number(process.env.PORT||3000),POSTER_TOKEN=process.env.POSTER_TOKEN||'',DEFAULT_FX=Number(process.env.MXN_PER_USD||18.5);
function json(res,code,body){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(body))}function num(v){const n=Number(v);return Number.isFinite(n)?n:0}function dateCompact(s){return String(s||'').replace(/-/g,'')}function first(o,keys){for(const k of keys)if(o&&o[k]!=null&&o[k]!=='')return o[k];return null}
async function poster(method,params={}){if(!POSTER_TOKEN)throw new Error('POSTER_TOKEN не задан в .env');const u=new URL(`https://joinposter.com/api/${method}`);u.searchParams.set('token',POSTER_TOKEN);for(const[k,v]of Object.entries(params))if(v!=null&&v!=='')u.searchParams.set(k,String(v));const r=await fetch(u,{headers:{Accept:'application/json'}}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Poster HTTP ${r.status}`);if(data.error)throw new Error(typeof data.error==='string'?data.error:JSON.stringify(data.error));return data.response??data}
function unwrapRows(v){if(Array.isArray(v))return v;if(!v||typeof v!=='object')return[];for(const k of['transactions','clients','spots','data','rows','items'])if(Array.isArray(v[k]))return v[k];return[]}
function txAmountMinor(t){return num(first(t,['payed_sum','payedSum','sum','transaction_sum','total_sum','total','amount']))}function txSpotId(t){return String(first(t,['spot_id','spotId','spot'])??'unknown')}function txClientId(t){const v=first(t,['client_id','clientId','client']);return v==null||String(v)==='0'?'':String(v)}
function normalizePosterDate(value){if(value==null||value==='')return null;if(typeof value==='number'||/^\d{10,13}$/.test(String(value).trim())){let n=Number(value);if(Number.isFinite(n)){if(n<1e12)n*=1000;const d=new Date(n);if(Number.isFinite(d.getTime()))return d.toISOString().slice(0,10)}}const raw=String(value).trim();let m=raw.match(/^(\d{4})[-/.]?(\d{2})[-/.]?(\d{2})(?:\D|$)/);if(m)return`${m[1]}-${m[2]}-${m[3]}`;m=raw.match(/^(\d{2})[./-](\d{2})[./-](\d{4})(?:\D|$)/);if(m)return`${m[3]}-${m[2]}-${m[1]}`;const d=new Date(raw);return Number.isFinite(d.getTime())?d.toISOString().slice(0,10):null}
function txDate(t){return normalizePosterDate(first(t,['date_close','close_date','dateClose','date_start','dateStart','date','created_at','createdAt','time','timestamp']))}function clientRegDate(c){return normalizePosterDate(first(c,['date_activ','date_active','date_created','created_at','createdAt','date_register','registration_date','date']))}function isClosed(t){const status=String(first(t,['status','transaction_status','state'])??'').toLowerCase();if(status&&['deleted','cancelled','canceled','void'].includes(status))return false;const del=first(t,['delete','deleted','is_deleted']);return!(String(del)==='1'||del===true)}
function dateRange(from,to){const out=[];let d=new Date(from+'T00:00:00'),e=new Date(to+'T00:00:00');while(d<=e){out.push(d.toISOString().slice(0,10));d.setDate(d.getDate()+1)}return out}
async function getDashboard(from,to,fx){const raw=await poster('dash.getTransactions',{dateFrom:dateCompact(from),dateTo:dateCompact(to)}),txs=unwrapRows(raw).filter(isClosed);let spots=[],clients=[];try{spots=unwrapRows(await poster('spots.getSpots'))}catch(_){}try{clients=unwrapRows(await poster('clients.getClients'))}catch(_){}const spotNames=new Map(spots.map(s=>[String(first(s,['spot_id','id'])??''),String(first(s,['spot_name','name'])||'')]));const clientDates=new Map(clients.map(c=>[String(first(c,['client_id','id'])??''),clientRegDate(c)]));const stores=new Map(),days=new Map();let totalMinor=0,invalidDates=0;const networkRegistered=new Set(),networkNew=new Set();
for(const t of txs){const amount=txAmountMinor(t),sid=txSpotId(t),day=txDate(t),cid=txClientId(t);totalMinor+=amount;if(!stores.has(sid))stores.set(sid,{spotId:sid,name:spotNames.get(sid)||`Магазин ${sid}`,revenueMinor:0,checks:0,registered:new Set(),newClients:new Set(),byDay:{}});const s=stores.get(sid);s.revenueMinor+=amount;s.checks++;if(!day){invalidDates++;continue}if(!s.byDay[day])s.byDay[day]={revenueMinor:0,checks:0,registered:new Set(),newClients:new Set()};const sd=s.byDay[day];sd.revenueMinor+=amount;sd.checks++;if(!days.has(day))days.set(day,{date:day,revenueMinor:0,checks:0,registered:new Set(),newClients:new Set()});const d=days.get(day);d.revenueMinor+=amount;d.checks++;
if(cid){s.registered.add(cid);sd.registered.add(cid);d.registered.add(cid);networkRegistered.add(cid);const rd=clientDates.get(cid);if(rd&&rd===day){s.newClients.add(cid);sd.newClients.add(cid);d.newClients.add(cid);networkNew.add(cid)}}}
const minorToMxn=v=>v/100,mxnToUsd=v=>v/fx,dates=dateRange(from,to);const normalizedStores=[...stores.values()].map(s=>{const revenueMxn=minorToMxn(s.revenueMinor),revenueUsd=mxnToUsd(revenueMxn),byDay={};for(const day of dates){const q=s.byDay[day]||{revenueMinor:0,checks:0,registered:new Set(),newClients:new Set()},usd=mxnToUsd(minorToMxn(q.revenueMinor));byDay[day]={revenueUsd:usd,checks:q.checks,avgCheckUsd:q.checks?usd/q.checks:0,registeredClients:q.registered.size,newClients:q.newClients.size}}return{spotId:s.spotId,name:s.name,revenueMxn,revenueUsd,checks:s.checks,avgCheckUsd:s.checks?revenueUsd/s.checks:0,share:totalMinor?s.revenueMinor/totalMinor:0,registeredClients:s.registered.size,newClients:s.newClients.size,byDay}}).sort((a,b)=>b.revenueUsd-a.revenueUsd);
const daily=dates.map(day=>{const d=days.get(day)||{date:day,revenueMinor:0,checks:0,registered:new Set(),newClients:new Set()},revenueUsd=mxnToUsd(minorToMxn(d.revenueMinor));return{date:day,checks:d.checks,revenueUsd,avgCheckUsd:d.checks?revenueUsd/d.checks:0,registeredClients:d.registered.size,newClients:d.newClients.size}}),totalUsd=mxnToUsd(minorToMxn(totalMinor));return{from,to,fx,currency:'USD',sourceCurrency:'MXN',dates,totals:{revenueUsd:totalUsd,checks:txs.length,avgCheckUsd:txs.length?totalUsd/txs.length:0,stores:normalizedStores.length,registeredClients:networkRegistered.size,newClients:networkNew.size},stores:normalizedStores,daily,diagnostics:{transactions:txs.length,invalidDates,clientsLoaded:clients.length}}}
function serveStatic(req,res,pathname){const target=pathname==='/'?'/index.html':pathname,file=path.normalize(path.join(ROOT,decodeURIComponent(target)));if(!file.startsWith(ROOT)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);return res.end('Not found')}const ext=path.extname(file).toLowerCase(),types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream'});fs.createReadStream(file).pipe(res)}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(u.pathname==='/api/poster/health')return json(res,200,{configured:Boolean(POSTER_TOKEN),fx:DEFAULT_FX});if(u.pathname==='/api/poster/dashboard'){const today=new Date().toISOString().slice(0,10),from=u.searchParams.get('from')||`${today.slice(0,8)}01`,to=u.searchParams.get('to')||today,fx=Number(u.searchParams.get('fx')||DEFAULT_FX);if(!Number.isFinite(fx)||fx<=0)return json(res,400,{error:'Некорректный MXN_PER_USD'});return json(res,200,await getDashboard(from,to,fx))}serveStatic(req,res,u.pathname)}catch(e){json(res,500,{error:e.message||String(e)})}}).listen(PORT,()=>console.log(`Cashflow / Poster dashboard: http://localhost:${PORT}/poster.html`));